import type {
  BackendName,
  BackendResult,
  ExportFormat,
  ExportResult,
  Hole,
  MeshDescriptor,
  ModelingBackend,
} from "~/types";

const wait = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

const COLORS = {
  box: "#a5b4fc",
  cylinder: "#86efac",
  sphere: "#7dd3fc",
  plate: "#fbbf24",
} as const;

let currentMesh: MeshDescriptor | null = null;

const uid = () => Math.random().toString(36).slice(2, 10);

function parseHoles(prompt: string): Hole[] {
  const p = prompt.toLowerCase();
  const countMatch = p.match(/(\d+)\s*(?:x\s*)?(?:holes|mounting)/);
  const count = countMatch ? Math.min(8, Math.max(1, Number(countMatch[1]))) : 4;
  const mSize = p.match(/m(\d+)/);
  const radius = mSize ? Number(mSize[1]) / 2 + 0.5 : 2.7;
  const offset = 30;
  const corners: [number, number, number][] = [
    [offset, offset, 0],
    [-offset, offset, 0],
    [offset, -offset, 0],
    [-offset, -offset, 0],
  ];
  return corners.slice(0, count).map((position) => ({ position, radius }));
}

function meshFromCreatePrompt(prompt: string): MeshDescriptor {
  const p = prompt.toLowerCase();
  const dims = p.match(/(\d+(?:\.\d+)?)\s*(?:mm)?\s*(?:x|by|×)\s*(\d+(?:\.\d+)?)/i);
  const thick = p.match(/(\d+(?:\.\d+)?)\s*mm\s*(?:thick|thickness)/i);

  if (/\b(sphere|ball)\b/.test(p)) {
    return { kind: "sphere", radius: 25, color: COLORS.sphere };
  }
  if (/\b(cylinder|pipe|rod|tube)\b/.test(p)) {
    return { kind: "cylinder", radius: 20, height: 60, color: COLORS.cylinder };
  }
  if (/\b(plate|bracket|mount|mounting)\b/.test(p)) {
    const [w, d] = dims ? [Number(dims[1]), Number(dims[2])] : [100, 60];
    const h = thick ? Number(thick[1]) : 8;
    return { kind: "plate", size: [w, d, h], color: COLORS.plate, holes: parseHoles(p) };
  }
  const [w, d] = dims ? [Number(dims[1]), Number(dims[2])] : [50, 50];
  return { kind: "box", size: [w, d, thick ? Number(thick[1]) : 50], color: COLORS.box };
}

function applyModifyPrompt(prompt: string, mesh: MeshDescriptor): MeshDescriptor {
  const p = prompt.toLowerCase();
  const next: MeshDescriptor = { ...mesh, holes: mesh.holes ? [...mesh.holes] : undefined };

  const factor = /(?:increase|larger|bigger|thicker|wider|taller|higher)\b/.test(p)
    ? 1.25
    : /(?:decrease|smaller|thinner|lower|reduce)\b/.test(p)
      ? 0.8
      : null;

  if (factor) {
    if (next.size) next.size = next.size.map((v) => Math.round(v * factor)) as [number, number, number];
    if (next.radius) next.radius = Math.round(next.radius * factor);
    if (next.height) next.height = Math.round(next.height * factor);
  }

  if (/\bhole/.test(p) && !next.holes) {
    next.holes = [{ position: [0, 0, 0], radius: 5 }];
  } else if (next.holes && /(?:remove|fill|delete)\b.*\bhole/.test(p)) {
    next.holes = undefined;
  }

  if (/\b(round|fillet|chamfer)\b/.test(p)) {
    next.color = "#f9a8d4";
  }
  return next;
}

function openscadCode(mesh: MeshDescriptor): string {
  const [w, d, h] = mesh.size ?? [50, 50, 50];
  const holes = mesh.holes ?? [];
  const body = (() => {
    switch (mesh.kind) {
      case "sphere":
        return `sphere(r = ${mesh.radius ?? 25}, $fn = 64);`;
      case "cylinder":
        return `cylinder(h = ${mesh.height ?? 60}, r = ${mesh.radius ?? 20}, $fn = 64);`;
      case "plate":
      case "box":
      default:
        return `cube([${w}, ${d}, ${h}], center = true);`;
    }
  })();
  const holeCode = holes
    .map(
      (hole) =>
        `    translate([${hole.position.join(", ")}]) cylinder(h = ${(mesh.size?.[2] ?? h) + 2}, r = ${hole.radius}, center = true, $fn = 32);`,
    )
    .join("\n");
  return `// Generated by AI CAD (OpenSCAD backend)\n${holes.length ? "difference() {\n" : ""}${holes.length ? "  " : ""}${body.replace(/\n/g, `\n${holes.length ? "  " : ""}`)}\n${holes.length ? holeCode + "\n}\n" : ""}`;
}

function build123dCode(mesh: MeshDescriptor): string {
  const [w, d, h] = mesh.size ?? [50, 50, 50];
  const holes = mesh.holes ?? [];
  const body = (() => {
    switch (mesh.kind) {
      case "sphere":
        return `part = Sphere(radius=${mesh.radius ?? 25})`;
      case "cylinder":
        return `part = Cylinder(radius=${mesh.radius ?? 20}, height=${mesh.height ?? 60})`;
      case "plate":
      case "box":
      default:
        return `part = Box(${w}, ${d}, ${h})`;
    }
  })();
  const holeCode = holes
    .map(
      (hole) =>
        `part -= Cylinder(radius=${hole.radius}, height=${(mesh.size?.[2] ?? h) + 2}).move_to(Vector(*[${hole.position.join(", ")}]))`,
    )
    .join("\n");
  return `# Generated by AI CAD (Build123D backend)\nfrom build123d import *\n\nwith BuildPart() as ctx:\n    ${body.split(" = ", 1)[0].replace("part", "ctx")}\n${holeCode ? holeCode + "\n" : ""}part = ctx.part\nprint(f"Volume: {part.volume:.2f} mm^3")\n`;
}

function describe(mesh: MeshDescriptor): string {
  switch (mesh.kind) {
    case "sphere":
      return `a sphere (r=${mesh.radius ?? 25} mm)`;
    case "cylinder":
      return `a cylinder (r=${mesh.radius ?? 20} mm, h=${mesh.height ?? 60} mm)`;
    case "plate": {
      const [w, d, h] = mesh.size ?? [100, 60, 8];
      const holeCount = mesh.holes?.length ?? 0;
      return `a ${w}×${d}×${h} mm plate${holeCount ? ` with ${holeCount} hole${holeCount > 1 ? "s" : ""}` : ""}`;
    }
    case "box":
    default: {
      const [w, d, h] = mesh.size ?? [50, 50, 50];
      return `a ${w}×${d}×${h} mm box`;
    }
  }
}

export class DummyBackend implements ModelingBackend {
  constructor(private backend: BackendName = "openscad") {}

  setBackend(b: BackendName) {
    this.backend = b;
  }

  async create(prompt: string): Promise<BackendResult> {
    await wait(900 + Math.random() * 700);
    const mesh = meshFromCreatePrompt(prompt);
    currentMesh = mesh;
    return {
      message: `Created ${describe(mesh)}.`,
      cadCode: this.code(mesh),
      language: this.backend,
      mesh,
    };
  }

  async modify(prompt: string): Promise<BackendResult> {
    await wait(700 + Math.random() * 600);
    if (!currentMesh) return this.create(prompt);
    const mesh = applyModifyPrompt(prompt, currentMesh);
    currentMesh = mesh;
    return {
      message: `Updated the model — now ${describe(mesh)}.`,
      cadCode: this.code(mesh),
      language: this.backend,
      mesh,
    };
  }

  render(): MeshDescriptor | null {
    return currentMesh;
  }

  async export(format: ExportFormat): Promise<ExportResult> {
    await wait(500);
    const sizeBytes = Math.round((currentMesh ? 24000 : 1024) * (format === "stl" ? 1 : 0.6));
    return { format, sizeBytes, filename: `model.${format}` };
  }

  private code(mesh: MeshDescriptor): string {
    return this.backend === "openscad" ? openscadCode(mesh) : build123dCode(mesh);
  }
}

export const dummyBackend = new DummyBackend();

export function newId(): string {
  return uid();
}

export function resetDummyState() {
  currentMesh = null;
}
