#!/usr/bin/env bash
# Regenerates server/backends/build123d_worker_asset.ts from build123d_worker.py.
# Run this after editing the worker script.
set -euo pipefail

cd "$(dirname "$0")/.."
SRC="server/backends/build123d_worker.py"
OUT="server/backends/build123d_worker_asset.ts"

if [ ! -f "$SRC" ]; then
  echo "error: $SRC not found" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 is required" >&2
  exit 1
fi

{
  printf 'import { Buffer } from "node:buffer";\n\n'
  printf '// Source: build123d_worker.py — inlined as base64 so the binary is fully self-contained.\n'
  printf '// Do not edit this file by hand; regenerate via scripts/sync-build123d-worker.sh after\n'
  printf '// changing build123d_worker.py.\n'
  printf 'const CHUNKS: readonly string[] = [\n'
  python3 -c "
import base64
with open('$SRC','rb') as f:
    b64 = base64.b64encode(f.read()).decode('ascii')
for i in range(0, len(b64), 112):
    print('  \"' + b64[i:i+112] + '\",')
"
  printf '];\n\n'
  printf 'export const BUILD123D_WORKER_SOURCE: string = Buffer.from(\n'
  printf '  CHUNKS.join(\"\"),\n'
  printf '  \"base64\",\n'
  printf ').toString(\"utf8\");\n'
} > "$OUT"

echo "wrote $OUT"
